### ISSUE TITLE
Gliffy UML Diagram

### ISSUE THREAD

**Issue by tramstheman** [North-Vine-Engineering/Optical-Barcode-Reader#3]
Project requirements state we need a UML diagram for the project. This should not be to difficult.

**Comment by tramstheman** [comment]
I have begun work on this.

**Comment by tramstheman** [comment]
This is complete and pending a pull request.

**Comment by tramstheman** [comment]
@KyleLuoma @akatrent @GEvanscsumb Does anyone else want to get their hands dirty with completing the UML? I can finish it but It is a nice skill to have and I wasn't sure if someone else wanted to get familiar with gliffy?

**Comment by GEvanscsumb** [comment]
I'll try my hand out at it. Is there a way to access what you've already done in gliffy?

**Comment by GEvanscsumb** [comment]
PR in #17
