### ISSUE TITLE
Main Test Driver

### ISSUE THREAD

**Issue by tramstheman** [North-Vine-Engineering/Optical-Barcode-Reader#5]
We need a test driver validating that all the implementation works to standards.

**Comment by tramstheman** [comment]
@KyleLuoma @akatrent @GEvanscsumb I forget if someone said they were working on this? or if they had done this. I remember something in chat. Also, don't forget to remove help wanted when you assign something to yourself.

**Comment by GEvanscsumb** [comment]
added in #14
